### ISSUE TITLE
Doesn't actually modify the file?

### ISSUE THREAD

**Issue by ilyvion** [NiklasEi/wasm-opt-action#2]
So, on my local machine; if I build my project and check the file size, I get
```
❯ trunk build --release
[...]
❯ ls -lh *.wasm
-rwxrwxrwx 1 alex alex 1.8M Aug  6 07:31 example_runner-fc39a6e8e639bcf6_bg.wasm
❯ wasm-opt .\dist\example_runner-fc39a6e8e639bcf6_bg.wasm -o .\dist\example_runner-fc39a6e8e639bcf6_bg.wasm --strip-debug -Oz
❯ ls -lh *.wasm
-rwxrwxrwx 1 alex alex 896K Aug  6 07:32 example_runner-fc39a6e8e639bcf6_bg.wasm
```
Nice. Basically a megabyte lighter. Now I want to do the same thing in my GitHub actions, so I have
```yaml
- name: Build examples
  run: |
      cd example_runner
      trunk build --release --public-url /bevy_doryen/examples/
      ls -lh dist/*.wasm
      cd ..

- name: Optimize examples WASM
  uses: NiklasEi/wasm-opt-action@v2
  with:
      file: example_runner/dist/*.wasm
      options: "--strip-debug -Oz"

- name: Finalize examples
  run: |
      ls -lh example_runner/dist/*.wasm
      mv example_runner/dist deploy/examples
```
(These `ls`-es aren't normally meant to be here, but I had to prove to myself somehow that this action wasn't doing anything.)
Here's what my action's output is:

First `ls`:
```
-rw-r--r-- 1 runner docker 1.8M Aug  6 05:25 dist/example_runner-465ddca1d27f94fa_bg.wasm
```

Second `ls`:
```
-rw-r--r-- 1 runner docker 1.8M Aug  6 05:25 example_runner/dist/example_runner-465ddca1d27f94fa_bg.wasm
```
And just for completion, here's the output of the `NiklasEi/wasm-opt-action` action itself:
```
Run NiklasEi/wasm-opt-action@v2
  with:
    file: example_runner/dist/*.wasm
    options: --strip-debug -Oz
  env:
    CARGO_TERM_COLOR: always
    CARGO_INCREMENTAL: 0
/usr/bin/docker run --name niklaseiwasmoptactionv220_37d9b6 --label 5bedb4 --workdir /github/workspace --rm -e "CARGO_TERM_COLOR" -e "CARGO_INCREMENTAL" -e "INPUT_FILE" -e "INPUT_OPTIONS" -e "INPUT_OUTPUT" -e "INPUT_OPTIMIZE_ALL" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/bevy_doryen/bevy_doryen":"/github/workspace" niklasei/wasm-opt-action:v2.2.0  "example_runner/dist/*.wasm" "" "" "--strip-debug -Oz"
Got arguments: [Some("example_runner/dist/*.wasm"), None, None, Some("--strip-debug -Oz")]
Searching for file matching '/github/workspace/example_runner/dist/*.wasm'
Optimizing '/github/workspace/example_runner/dist/example_runner-465ddca1d27f94fa_bg.wasm'
Writing optimized wasm file to '/github/workspace/example_runner/dist/example_runner-465ddca1d27f94fa_bg.wasm'
Executing 'wasm-opt /github/workspace/example_runner/dist/example_runner-465ddca1d27f94fa_bg.wasm -o /github/workspace/example_runner/dist/example_runner-465ddca1d27f94fa_bg.wasm --strip-debug -Oz'
```

Finally, here's the GH action run as a whole if you want to have a look at that, too: <https://github.com/alexschrod/bevy_doryen/actions/runs/5774820846/job/15652186066>
